// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmhkggqgsfwfntayfaly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtaGtnZ3Fnc2Z3Zm50YXlmYWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzQ3OTAsImV4cCI6MjA2MDA1MDc5MH0.l2rO-JgkzFqpRUv4XQIsTMLCx63GBMXyFV1gCxmlvJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);